In [19]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [20]:
train=pd.read_csv("fordTrain.csv")
test=pd.read_csv("fordTest.csv")

In [21]:
train.head()

,TrialID,ObsNum,IsAlert,P1,P2,P3,P4,P5,P6,P7,...,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11
0,0,0,0,34.7406,9.84593,1400,42.8571,0.290601,572,104.895,...,0.175,752,5.99375,0,2005,0,13.4,0,4,14.8004
1,0,1,0,34.4215,13.41120,1400,42.8571,0.290601,572,104.895,...,0.455,752,5.99375,0,2007,0,13.4,0,4,14.7729
2,0,2,0,34.3447,15.18520,1400,42.8571,0.290601,576,104.167,...,0.280,752,5.99375,0,2011,0,13.4,0,4,14.7736
3,0,3,0,34.3421,8.84696,1400,42.8571,0.290601,576,104.167,...,0.070,752,5.99375,0,2015,0,13.4,0,4,14.7667
4,0,4,0,34.3322,14.69940,1400,42.8571,0.290601,576,104.167,...,0.175,752,5.99375,0,2017,0,13.4,0,4,14.7757

In [22]:
test.head()

,TrialID,ObsNum,IsAlert,P1,P2,P3,P4,P5,P6,P7,...,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11
0,0,0,?,38.4294,10.9435,1000,60.0,0.302277,508,118.110,...,0.00,255,4.50625,0,2127,0,17.6,0,4,16.1937
1,0,1,?,38.3609,15.3212,1000,60.0,0.302277,508,118.110,...,0.00,255,4.50625,0,2127,0,17.6,0,4,16.1744
2,0,2,?,38.2342,11.5140,1000,60.0,0.302277,508,118.110,...,0.07,255,4.50625,0,2131,0,17.6,0,4,16.1602
3,0,3,?,37.9304,12.2615,1000,60.0,0.302277,508,118.110,...,0.07,255,4.50625,0,2131,0,17.6,0,4,16.1725
4,0,4,?,37.8085,12.3666,1000,60.0,0.302277,504,119.048,...,0.00,255,4.50625,0,2136,0,17.6,0,4,16.1459

In [23]:
test=test.drop('IsAlert',axis=1)

In [24]:
test

,TrialID,ObsNum,P1,P2,P3,P4,P5,P6,P7,P8,...,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11
0,0,0,38.4294,10.94350,1000,60.0000,0.302277,508,118.1100,0,...,0.00,255,4.50625,0,2127,0,17.6,0,4,16.1937
1,0,1,38.3609,15.32120,1000,60.0000,0.302277,508,118.1100,0,...,0.00,255,4.50625,0,2127,0,17.6,0,4,16.1744
2,0,2,38.2342,11.51400,1000,60.0000,0.302277,508,118.1100,0,...,0.07,255,4.50625,0,2131,0,17.6,0,4,16.1602
3,0,3,37.9304,12.26150,1000,60.0000,0.302277,508,118.1100,0,...,0.07,255,4.50625,0,2131,0,17.6,0,4,16.1725
4,0,4,37.8085,12.36660,1000,60.0000,0.302277,504,119.0480,0,...,0.00,255,4.50625,0,2136,0,17.6,0,4,16.1459
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120835,99,1206,37.3798,17.40260,892,67.2646,0.131030,752,79.7872,0,...,-0.07,255,0.00000,0,658,0,0.0,0,1,16.6850
120836,99,1207,37.1653,5.37419,892,67.2646,0.131030,752,79.7872,0,...,-0.07,255,0.00000,0,657,0,0.0,0,1,16.6840
120837,99,1208,36.9131,9.26657,892,67.2646,0.131030,752,79.7872,0,...,-0.07,255,0.00000,0,655,0,0.0,0,1,16.6487
120838,99,1209,36.6297,10.41710,892,67.2646,0.131030,752,79.7872,0,...,-0.07,240,0.00000,0,657,0,0.0,0,1,16.6314
120839,99,1210,36.6297,10.41710,892,67.2646,0.131030,752,79.7872,0,...,-0.07,240,0.00000,0,657,0,0.0,0,1,16.6314

In [25]:
test.shape ,train.shape

((120840, 32), (604329, 33))

In [26]:
train.isnull().sum()

TrialID    0
ObsNum     0
IsAlert    0
P1         0
P2         0
P3         0
P4         0
P5         0
P6         0
P7         0
P8         0
E1         0
E2         0
E3         0
E4         0
E5         0
E6         0
E7         0
E8         0
E9         0
E10        0
E11        0
V1         0
V2         0
V3         0
V4         0
V5         0
V6         0
V7         0
V8         0
V9         0
V10        0
V11        0
dtype: int64

In [27]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 604329 entries, 0 to 604328
Data columns (total 33 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   TrialID  604329 non-null  int64
 1   ObsNum   604329 non-null  int64
 2   IsAlert  604329 non-null  int64
 3   P1       604329 non-null  float64
 4   P2       604329 non-null  float64
 5   P3       604329 non-null  int64
 6   P4       604329 non-null  float64
 7   P5       604329 non-null  float64
 8   P6       604329 non-null  int64
 9   P7       604329 non-null  float64
 10  P8       604329 non-null  int64
 11  E1       604329 non-null  float64
 12  E2       604329 non-null  float64
 13  E3       604329 non-null  int64
 14  E4       604329 non-null  int64
 15  E5       604329 non-null  float64
 16  E6       604329 non-null  int64
 17  E7       604329 non-null  int64
 18  E8       604329 non-null  int64
 19  E9       604329 non-null  int64
 20  E10      604329 non-null  int64
 21  E11      604329 non-null  float64
 22  V1       604329 non-null  float64
 23  V2       604329 non-null  float64
 24  V3       604329 non-null  int64
 25  V4       604329 non-null  float64
 26  V5       604329 non-null  int64
 27  V6       604329 non-null  int64
 28  V7       604329 non-null  int64
 29  V8       604329 non-null  float64
 30  V9       604329 non-null  int64
 31  V10      604329 non-null  int64
 32  V11      604329 non-null  float64
dtypes: float64(14), int64(19)
memory usage: 152.2 MB

In [28]:
train=train.drop(['TrialID','ObsNum'],axis=1)

In [29]:
train.head()

,IsAlert,P1,P2,P3,P4,P5,P6,P7,P8,E1,...,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11
0,0,34.7406,9.84593,1400,42.8571,0.290601,572,104.895,0,0.0,...,0.175,752,5.99375,0,2005,0,13.4,0,4,14.8004
1,0,34.4215,13.41120,1400,42.8571,0.290601,572,104.895,0,0.0,...,0.455,752,5.99375,0,2007,0,13.4,0,4,14.7729
2,0,34.3447,15.18520,1400,42.8571,0.290601,576,104.167,0,0.0,...,0.280,752,5.99375,0,2011,0,13.4,0,4,14.7736
3,0,34.3421,8.84696,1400,42.8571,0.290601,576,104.167,0,0.0,...,0.070,752,5.99375,0,2015,0,13.4,0,4,14.7667
4,0,34.3322,14.69940,1400,42.8571,0.290601,576,104.167,0,0.0,...,0.175,752,5.99375,0,2017,0,13.4,0,4,14.7757

In [30]:
test=test.drop(['TrialID','ObsNum'],axis=1)

In [31]:
test.head()

,P1,P2,P3,P4,P5,P6,P7,P8,E1,E2,...,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11
0,38.4294,10.9435,1000,60.0,0.302277,508,118.110,0,0.0,0.0,...,0.00,255,4.50625,0,2127,0,17.6,0,4,16.1937
1,38.3609,15.3212,1000,60.0,0.302277,508,118.110,0,0.0,0.0,...,0.00,255,4.50625,0,2127,0,17.6,0,4,16.1744
2,38.2342,11.5140,1000,60.0,0.302277,508,118.110,0,0.0,0.0,...,0.07,255,4.50625,0,2131,0,17.6,0,4,16.1602
3,37.9304,12.2615,1000,60.0,0.302277,508,118.110,0,0.0,0.0,...,0.07,255,4.50625,0,2131,0,17.6,0,4,16.1725
4,37.8085,12.3666,1000,60.0,0.302277,504,119.048,0,0.0,0.0,...,0.00,255,4.50625,0,2136,0,17.6,0,4,16.1459

In [32]:
train.skew()

IsAlert    -0.319185
P1          2.445986
P2          0.863450
P3          0.507984
P4          0.643117
P5         20.225034
P6         89.789752
P7          1.937124
P8          0.000000
E1          0.766075
E2          0.754220
E3          3.352342
E4         -2.467771
E5          0.175100
E6         -0.469872
E7          2.844119
E8          2.200218
E9         -2.292728
E10        -0.433540
E11         4.062888
V1         -0.941470
V2         -0.759452
V3          0.261053
V4          5.144928
V5          1.667496
V6         -0.871827
V7          0.000000
V8          0.406715
V9          0.000000
V10        -1.172114
V11        21.165566
dtype: float64

In [33]:
from sklearn.model_selection import train_test_split
X=train.drop('IsAlert',axis=1)
y=train['IsAlert']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4)

In [34]:
from sklearn.ensemble import RandomForestClassifier

In [35]:
model=RandomForestClassifier()
model.fit(X_train,y_train)

RandomForestClassifier()

In [36]:
y_pred=model.predict(X_test)

In [37]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9912009994539407