In [3]:
import pandas as pd
import os

In [4]:
os.listdir(".")

['.ipynb_checkpoints',
 'example.csv',
 'solution.ipynb',
 'template.csv',
 'tourism_data.csv']

In [5]:
example=pd.read_csv("example.csv")
template=pd.read_csv("template.csv")
toursim_data=pd.read_csv("tourism_data.csv")

In [6]:
example.head()

,Y1,Y2,Y3,Y4,Y5,Y6,Y7,Y8,Y9,Y10,...,Y509,Y510,Y511,Y512,Y513,Y514,Y515,Y516,Y517,Y518
0,38805.10294,268386.29,214382.6,118503.4919,44425.4964,2688.62,8402.19,8510.26,9269.78,3266.34,...,183739.2,2065514.64,1675.59,1579.64,1609.94,1921.02,1658.42,1372.59,1333.2,1113.02
1,39189.31188,271043.58,216505.2,119676.7938,44865.3528,2715.24,8485.38,8594.52,9361.56,3298.68,...,185558.4,2085965.28,1692.18,1595.28,1625.88,1940.04,1674.84,1386.18,1346.4,1124.04
2,39573.52082,273700.87,218627.8,120850.0957,45305.2092,2741.86,8568.57,8678.78,9453.34,3331.02,...,187377.6,2106415.92,1708.77,1610.92,1641.82,1959.06,1691.26,1399.77,1359.6,1135.06
3,39957.72976,276358.16,220750.4,122023.3976,45745.0656,2768.48,8651.76,8763.04,9545.12,3363.36,...,189196.8,2126866.56,1725.36,1626.56,1657.76,1978.08,1707.68,1413.36,1372.8,1146.08

In [7]:
template.head()

Empty DataFrame
Columns: [Y1, Y2, Y3, Y4, Y5, Y6, Y7, Y8, Y9, Y10, Y11, Y12, Y13, Y14, Y15, Y16, Y17, Y18, Y19, Y20, Y21, Y22, Y23, Y24, Y25, Y26, Y27, Y28, Y29, Y30, Y31, Y32, Y33, Y34, Y35, Y36, Y37, Y38, Y39, Y40, Y41, Y42, Y43, Y44, Y45, Y46, Y47, Y48, Y49, Y50, Y51, Y52, Y53, Y54, Y55, Y56, Y57, Y58, Y59, Y60, Y61, Y62, Y63, Y64, Y65, Y66, Y67, Y68, Y69, Y70, Y71, Y72, Y73, Y74, Y75, Y76, Y77, Y78, Y79, Y80, Y81, Y82, Y83, Y84, Y85, Y86, Y87, Y88, Y89, Y90, Y91, Y92, Y93, Y94, Y95, Y96, Y97, Y98, Y99, Y100, ...]
Index: []

[0 rows x 518 columns]

In [12]:
toursim_data.head(100)

,Y1,Y2,Y3,Y4,Y5,Y6,Y7,Y8,Y9,Y10,...,Y509,Y510,Y511,Y512,Y513,Y514,Y515,Y516,Y517,Y518
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,43595.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,43032.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,47474.0,27829.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,55141.0,35865.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,62946.0,40311.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,66920.0,47186.0,NaN,NaN,850.0,2901.0,NaN,NaN,296.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,77191.0,56664.0,NaN,NaN,863.0,2902.0,NaN,NaN,399.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,89661.0,68040.0,NaN,NaN,862.0,3024.0,NaN,NaN,474.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,101373.0,64008.0,NaN,NaN,868.0,3102.0,NaN,NaN,591.0,...,60528.0,465163.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,123904.0,79400.0,NaN,NaN,808.0,3068.0,NaN,1860.0,701.0,...,58871.0,478037.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,149453.0,96731.0,NaN,NaN,757.0,3105.0,NaN,1806.0,849.0,...,53889.0,481726.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,168672.0,100517.0,NaN,NaN,748.0,3193.0,NaN,1725.0,963.0,...,52694.0,508465.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,200977.0,89685.0,NaN,NaN,832.0,3272.0,NaN,1643.0,1068.0,...,53708.0,567611.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,192985.0,105709.0,NaN,NaN,931.0,3511.0,NaN,1660.0,1216.0,...,62441.0,669558.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,205667.0,120532.0,18467.00,11094.00,980.0,3720.0,NaN,1785.0,1537.0,...,75867.0,733424.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,187450.0,127457.0,24172.00,10274.00,987.0,3667.0,NaN,2108.0,1915.0,...,113459.0,844313.0,1520.0,1668.0,1526.0,653.0,1476.0,1121.0,1531.0,1389.0
28,NaN,165613.0,117306.0,35522.00,10333.00,1112.0,4235.0,NaN,2721.0,2133.0,...,116965.0,864892.0,1373.0,1485.0,1335.0,706.0,1127.0,1118.0,1397.0,1416.0
29,NaN,200871.0,106498.0,36823.00,9550.00,1221.0,4889.0,NaN,3523.0,2024.0,...,126164.0,901078.0,1407.0,1503.0,1417.0,588.0,893.0,1549.0,1134.0,1573.0
30,NaN,229394.0,79543.0,37112.00,9525.00,1309.0,5711.0,NaN,4093.0,2059.0,...,141130.0,976010.0,1406.0,1454.0,1295.0,726.0,808.0,1234.0,1290.0,1544.0
31,NaN,283229.0,106599.0,47970.00,9132.00,1408.0,6236.0,NaN,4437.0,2149.0,...,129287.0,963470.0,1285.0,1302.0,1402.0,1139.0,1471.0,1290.0,1799.0,1516.0
32,25092.2284,289717.0,126328.0,78032.00,11546.00,1351.0,5918.0,5639.0,3948.0,2193.0,...,121750.0,1055681.0,1604.0,1065.0,1280.0,1571.0,1079.0,1755.0,1087.0,1499.0
33,24271.5134,270585.0,160896.0,96664.00,13298.00,1537.0,6589.0,5696.0,4324.0,2312.0,...,116207.0,1156978.0,1491.0,1591.0,1361.0,1565.0,1224.0,1745.0,1034.0,1504.0
34,25828.9883,279514.0,174346.0,91092.00,13188.00,1684.0,6765.0,6010.0,4364.0,2329.0,...,141650.0,1322565.0,1324.0,1638.0,1076.0,1553.0,1621.0,1892.0,1460.0,1343.0
35,27697.5047,349768.0,176014.0,91106.00,13020.00,1880.0,7259.0,6257.0,5127.0,2456.0,...,151102.0,1408795.0,1468.0,1370.0,1589.0,1538.0,1099.0,1515.0,1717.0,1583.0
36,27956.2276,339689.0,184417.0,96137.00,15277.00,1864.0,6583.0,6565.0,6016.0,2501.0,...,169693.0,1528720.0,1186.0,1433.0,1193.0,1837.0,1078.0,1490.0,1734.0,1772.0
37,29924.4321,331610.0,174960.0,76376.00,15424.00,1925.0,6407.0,6780.0,6940.0,2412.0,...,170479.0,1497183.0,1494.0,1063.0,984.0,1629.0,1617.0,1438.0,1050.0,1676.0
38,30216.8321,351175.0,174960.0,78519.00,14280.00,2340.0,6442.0,7181.0,7781.0,2613.0,...,176856.0,1484512.0,1622.0,1293.0,1417.0,1603.0,1655.0,1266.0,1864.0,1423.0
39,32613.4968,450569.0,104885.0,88534.00,14929.00,2675.0,7069.0,7505.0,8527.0,2885.0,...,176246.0,1607241.0,1647.0,1367.0,1292.0,1587.0,1466.0,1285.0,1721.0,1751.0
40,36053.1674,421513.0,188069.0,97115.00,17057.00,2860.0,7595.0,8160.0,8971.0,3125.0,...,149513.0,1786765.0,1366.0,1568.0,1411.0,1556.0,1625.0,1185.0,1628.0,1385.0
41,38472.7532,426166.0,236275.0,96381.00,15798.00,2865.0,8250.0,8771.0,9300.0,3253.0,...,169667.0,1909381.0,1430.0,1603.0,1702.0,1989.0,1596.0,1455.0,1399.0,1229.0
42,38420.8940,265729.0,212260.0,117330.19,43985.64,2662.0,8319.0,8426.0,9178.0,3234.0,...,181920.0,2045064.0,1659.0,1564.0,1594.0,1902.0,1642.0,1359.0,1320.0,1102.0