In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
train=pd.read_csv("train.csv")
test=pd.read_csv("test.csv")

In [4]:
train

,file,NumberOfConnectedComponents_1[0],NumberOfHoles_1[0],SpatialMoment00,SpatialMoment10,SpatialMoment20,SpatialMoment30,SpatialMoment01,SpatialMoment11,SpatialMoment21,...,chaincode8order4_4096[4086],chaincode8order4_4096[4087],chaincode8order4_4096[4088],chaincode8order4_4096[4089],chaincode8order4_4096[4090],chaincode8order4_4096[4091],chaincode8order4_4096[4092],chaincode8order4_4096[4093],chaincode8order4_4096[4094],chaincode8order4_4096[4095]
0,031_1,79,39,36342,40878300.0,5.766330e+10,8.922610e+13,8503300.0,9.584780e+09,1.359450e+13,...,0.000833,0.010444,0.004995,0.000605,0.000151,0.000000,0.000076,0,0.009006,0.023008
1,031_2,109,34,50885,58117600.0,8.206650e+10,1.299340e+14,14504800.0,1.566150e+10,2.111950e+13,...,0.000847,0.005531,0.006096,0.000395,0.000113,0.000000,0.000056,0,0.004967,0.024271
2,034_1,90,33,38049,47212200.0,7.332970e+10,1.245510e+14,9837350.0,1.339610e+10,2.161680e+13,...,0.001203,0.005886,0.006646,0.000506,0.000190,0.000063,0.000063,0,0.006076,0.029242
3,034_2,124,37,53227,56413100.0,7.909480e+10,1.253190e+14,16302000.0,1.764590e+10,2.508830e+13,...,0.000681,0.006220,0.006811,0.000499,0.000045,0.000182,0.000045,0,0.005766,0.032056
4,035_1,83,63,34948,41224800.0,5.967650e+10,9.597570e+13,3981670.0,4.859740e+09,6.973220e+12,...,0.000950,0.005701,0.008314,0.000238,0.000079,0.000000,0.000158,0,0.006492,0.025495
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,093_2,108,51,68720,79047200.0,1.126060e+11,1.766780e+14,14541800.0,1.749890e+10,2.514090e+13,...,0.002361,0.011767,0.004643,0.000240,0.000000,0.000000,0.000000,0,0.008525,0.023973
104,095_1,86,47,40893,49291300.0,7.428850e+10,1.247980e+14,6542090.0,7.850340e+09,1.151650e+13,...,0.001238,0.006778,0.006909,0.000912,0.000196,0.000000,0.000000,0,0.006974,0.033240
105,095_2,114,59,45194,54907800.0,8.636160e+10,1.524030e+14,9130980.0,1.164160e+10,1.902440e+13,...,0.001048,0.007169,0.006728,0.000607,0.000221,0.000110,0.000000,0,0.006728,0.027131
106,096_1,69,24,34247,41952600.0,6.438260e+10,1.110490e+14,8806340.0,9.860630e+09,1.395300e+13,...,0.000560,0.008242,0.006562,0.000560,0.000240,0.000080,0.000000,0,0.007362,0.032888
107,096_2,99,24,46699,54370400.0,8.417040e+10,1.473210e+14,10219500.0,1.239380e+10,1.977080e+13,...,0.000977,0.008595,0.008334,0.000456,0.000065,0.000000,0.000000,0,0.007293,0.032947

In [5]:
test

,file,NumberOfConnectedComponents_1[0],NumberOfHoles_1[0],SpatialMoment00,SpatialMoment10,SpatialMoment20,SpatialMoment30,SpatialMoment01,SpatialMoment11,SpatialMoment21,...,chaincode8order4_4096[4086],chaincode8order4_4096[4087],chaincode8order4_4096[4088],chaincode8order4_4096[4089],chaincode8order4_4096[4090],chaincode8order4_4096[4091],chaincode8order4_4096[4092],chaincode8order4_4096[4093],chaincode8order4_4096[4094],chaincode8order4_4096[4095]
0,AA,118,52,56889,62124300.0,8.823880e+10,1.415410e+14,19188800.0,1.936350e+10,2.564450e+13,...,0.001281,0.012998,0.005835,0.000427,0.000380,0.000047,0.000000,0,0.009535,0.028843
1,AB,101,62,61865,71838700.0,1.121300e+11,2.007610e+14,15199600.0,1.644090e+10,2.569500e+13,...,0.001313,0.006864,0.006186,0.000339,0.000085,0.000042,0.000000,0,0.006949,0.035168
2,AC,93,49,51817,52009200.0,6.959920e+10,1.079290e+14,10744900.0,9.410890e+09,1.140080e+13,...,0.002207,0.012328,0.005599,0.000646,0.000054,0.000054,0.000000,0,0.009690,0.023417
3,AD,97,55,64951,76992800.0,1.264340e+11,2.374740e+14,16031500.0,1.978720e+10,3.388020e+13,...,0.001183,0.011451,0.005746,0.000507,0.000338,0.000042,0.000042,0,0.009549,0.034774
4,AE,107,46,58168,72143000.0,1.108440e+11,1.897170e+14,13168700.0,1.703770e+10,2.732670e+13,...,0.001229,0.010127,0.006292,0.000344,0.000098,0.000000,0.000000,0,0.007669,0.026497
5,AF,106,66,74026,83038300.0,1.271770e+11,2.223160e+14,20131700.0,1.973330e+10,2.811100e+13,...,0.001383,0.009567,0.006109,0.000423,0.000115,0.000038,0.000077,0,0.007799,0.028277
6,AG,105,40,46455,50222100.0,7.279060e+10,1.224330e+14,7903270.0,7.675780e+09,1.050990e+13,...,0.000992,0.009157,0.009507,0.000817,0.000000,0.000000,0.000058,0,0.008282,0.044678
7,AH,108,57,60251,66345700.0,1.006100e+11,1.752310e+14,11142000.0,1.009740e+10,1.404060e+13,...,0.000744,0.007492,0.009279,0.000347,0.000000,0.000000,0.000050,0,0.006301,0.041282
8,AI,105,26,44920,52960600.0,8.234440e+10,1.435350e+14,8314140.0,9.285610e+09,1.436050e+13,...,0.000467,0.002938,0.007814,0.000334,0.000134,0.000000,0.000067,0,0.003473,0.028316
9,AJ,106,21,30754,34580600.0,4.832530e+10,7.668500e+13,8435310.0,7.853370e+09,9.510120e+12,...,0.001896,0.008619,0.007930,0.000603,0.000431,0.000172,0.000000,0,0.007154,0.028443
10,AK,97,23,43629,48582000.0,6.964270e+10,1.125530e+14,10318700.0,1.055340e+10,1.461460e+13,...,0.001168,0.013954,0.005841,0.001233,0.000260,0.000000,0.000000,0,0.010579,0.033489
11,AM,105,67,61539,73556100.0,1.150610e+11,2.022880e+14,18796400.0,1.882240e+10,2.695210e+13,...,0.001144,0.008333,0.005514,0.000368,0.000041,0.000041,0.000041,0,0.006699,0.022425
12,AN,99,34,54558,60274700.0,8.796570e+10,1.467590e+14,11988700.0,1.043610e+10,1.344910e+13,...,0.001043,0.009542,0.008134,0.000209,0.000104,0.000000,0.000104,0,0.009594,0.041973
13,AO,102,42,42889,50120800.0,7.592280e+10,1.314700e+14,9014920.0,8.755610e+09,1.168920e+13,...,0.001748,0.005908,0.005667,0.000603,0.000241,0.000060,0.000000,0,0.005426,0.025562
14,AP,109,68,44411,47660700.0,7.135110e+10,1.227050e+14,13307600.0,1.075870e+10,1.354980e+13,...,0.000886,0.006199,0.004428,0.000387,0.000055,0.000000,0.000000,0,0.005479,0.019205
15,AQ,102,56,49620,53710300.0,7.761380e+10,1.275320e+14,10918900.0,1.027670e+10,1.412940e+13,...,0.000864,0.005993,0.006533,0.000486,0.000108,0.000000,0.000000,0,0.005723,0.020463
16,AR,106,44,54503,62950900.0,8.780940e+10,1.372020e+14,9631440.0,1.083110e+10,1.467050e+13,...,0.002762,0.012610,0.006485,0.000540,0.000060,0.000060,0.000000,0,0.010208,0.030685
17,AS,102,52,38116,38839200.0,5.124390e+10,7.697930e+13,6611530.0,6.263630e+09,7.959920e+12,...,0.001350,0.005757,0.009311,0.000569,0.000000,0.000071,0.000142,0,0.006254,0.036532
18,AT,98,45,57586,58342500.0,7.914070e+10,1.237240e+14,13159400.0,1.318080e+10,1.789420e+13,...,0.001785,0.012449,0.004295,0.000579,0.000145,0.000000,0.000000,0,0.008251,0.021424
19,AU,99,24,36393,40599200.0,5.633100e+10,8.786830e+13,6918500.0,7.072100e+09,9.213140e+12,...,0.001350,0.008884,0.006965,0.000711,0.000426,0.000000,0.000000,0,0.007604,0.028214
20,AV,102,32,34239,45767700.0,7.638530e+10,1.406500e+14,5968810.0,6.747630e+09,1.042090e+13,...,0.001080,0.006046,0.006837,0.000936,0.000360,0.000144,0.000000,0,0.005254,0.030517
21,AW,118,78,50574,66703100.0,1.084280e+11,1.959950e+14,8398010.0,1.017840e+10,1.603350e+13,...,0.001534,0.014067,0.006875,0.000899,0.000106,0.000053,0.000106,0,0.011052,0.034638
22,AX,104,37,42790,48764200.0,7.214240e+10,1.197800e+14,10168300.0,1.118950e+10,1.591570e+13,...,0.001015,0.008060,0.005355,0.001015,0.000056,0.000000,0.000113,0,0.007384,0.028634
23,AY,98,27,52035,57427500.0,8.537930e+10,1.459310e+14,13552100.0,1.285890e+10,1.813410e+13,...,0.000840,0.009190,0.004674,0.000263,0.000105,0.000000,0.000105,0,0.006039,0.017644
24,AZ,99,49,49631,57705100.0,8.999500e+10,1.620640e+14,9876660.0,1.066470e+10,1.578640e+13,...,0.000683,0.006004,0.005321,0.000537,0.000000,0.000049,0.000000,0,0.004979,0.023481
25,BA,99,32,40146,43135400.0,5.971260e+10,9.332460e+13,11375600.0,1.148150e+10,1.519300e+13,...,0.000475,0.005086,0.006782,0.000543,0.000339,0.000000,0.000000,0,0.005086,0.033161
26,BB,124,54,50616,60389700.0,9.107200e+10,1.535420e+14,13226500.0,1.478350e+10,2.155560e+13,...,0.001439,0.010396,0.006398,0.000960,0.000320,0.000160,0.000000,0,0.008957,0.029589
27,BC,101,31,34611,44012900.0,6.936640e+10,1.221730e+14,8441050.0,9.286950e+09,1.337790e+13,...,0.001120,0.005391,0.008401,0.001190,0.000210,0.000070,0.000070,0,0.006371,0.037244
28,BD,100,42,58901,69754800.0,1.104780e+11,1.969160e+14,17552100.0,2.119780e+10,3.437940e+13,...,0.001736,0.011083,0.005618,0.000460,0.000153,0.000000,0.000051,0,0.008223,0.022625
29,BE,101,40,43922,47728700.0,6.774170e+10,1.080090e+14,10230900.0,1.032890e+10,1.431840e+13,...,0.000473,0.002433,0.011152,0.000270,0.000203,0.000000,0.000135,0,0.002095,0.026158
30,BF,101,40,51227,53647700.0,7.389080e+10,1.169700e+14,13096500.0,1.134100e+10,1.336230e+13,...,0.001192,0.007094,0.008059,0.000511,0.000057,0.000057,0.000000,0,0.007321,0.044325
31,BG,104,46,59575,63909000.0,9.111920e+10,1.460420e+14,15820500.0,1.609150e+10,2.293440e+13,...,0.001227,0.012864,0.005941,0.000540,0.000000,0.000000,0.000000,0,0.010507,0.028526
32,BH,102,27,39819,45247300.0,6.635230e+10,1.105690e+14,7210850.0,7.324590e+09,9.985300e+12,...,0.002502,0.009294,0.006935,0.000858,0.000214,0.000000,0.000000,0,0.006578,0.023236
33,BI,102,38,43148,53947300.0,8.775790e+10,1.599250e+14,8611890.0,1.073350e+10,1.732020e+13,...,0.001740,0.009570,0.005756,0.000535,0.000268,0.000000,0.000000,0,0.006492,0.015058
34,BK,110,44,38142,45591500.0,6.805420e+10,1.134340e+14,7391190.0,8.525030e+09,1.226030e+13,...,0.000666,0.009396,0.005931,0.000600,0.000267,0.000067,0.000000,0,0.009062,0.031252
35,BL,104,33,34859,35178700.0,4.519910e+10,6.546830e+13,5905110.0,5.645050e+09,6.895650e+12,...,0.000575,0.007833,0.004024,0.000647,0.000359,0.000072,0.000072,0,0.005390,0.018110
36,BM,101,39,44381,42110100.0,5.326470e+10,7.699130e+13,6341660.0,5.660160e+09,7.154420e+12,...,0.001324,0.009961,0.007502,0.000820,0.000315,0.000063,0.000063,0,0.008196,0.038520
37,BN,103,54,41713,47426600.0,7.111470e+10,1.189730e+14,9454130.0,1.102480e+10,1.733600e+13,...,0.001324,0.009145,0.006437,0.000541,0.000120,0.000000,0.000060,0,0.008784,0.042113
38,BO,98,46,62379,63114800.0,8.817900e+10,1.441890e+14,12266900.0,1.074710e+10,1.382280e+13,...,0.001712,0.009161,0.007218,0.000324,0.000185,0.000000,0.000046,0,0.007218,0.022994
39,BP,101,32,44188,44530000.0,6.303920e+10,1.028330e+14,8913260.0,7.844190e+09,1.055470e+13,...,0.001584,0.011721,0.006716,0.000887,0.000127,0.000063,0.000063,0,0.009693,0.029840
40,BQ,99,31,42073,49864300.0,7.665690e+10,1.320750e+14,10111300.0,1.184970e+10,1.821320e+13,...,0.001524,0.008934,0.007549,0.000970,0.000208,0.000069,0.000139,0,0.009280,0.033520
41,BR,113,61,58768,71777200.0,1.051560e+11,1.713610e+14,13664700.0,1.648380e+10,2.397260e+13,...,0.000936,0.006108,0.006714,0.000275,0.000110,0.000000,0.000110,0,0.005723,0.024488
42,BS,100,43,49517,63108300.0,1.012210e+11,1.822720e+14,12891700.0,1.487110e+10,2.195610e+13,...,0.000971,0.007931,0.005072,0.000701,0.000162,0.000000,0.000054,0,0.006313,0.021906
43,BT,108,36,42925,51048000.0,7.957530e+10,1.414040e+14,9402000.0,9.935770e+09,1.405260e+13,...,0.000787,0.006438,0.005579,0.000143,0.000143,0.000000,0.000072,0,0.005150,0.018956
44,BU,100,47,64266,74730400.0,1.137170e+11,1.967210e+14,15765600.0,1.560810e+10,2.228450e+13,...,0.000777,0.009626,0.005827,0.000388,0.000129,0.000000,0.000043,0,0.007424,0.028316
45,BV,100,25,38072,40135600.0,5.338830e+10,8.090870e+13,7298660.0,6.555340e+09,7.877050e+12,...,0.001455,0.009037,0.005744,0.000766,0.000230,0.000000,0.000000,0,0.006586,0.021136
46,BW,96,53,55913,71312400.0,1.177930e+11,2.176520e+14,11674000.0,1.239270e+10,1.861710e+13,...,0.001087,0.007313,0.006275,0.000445,0.000148,0.000049,0.000049,0,0.005781,0.019024
47,BX,101,61,57730,55165000.0,7.061340e+10,1.035530e+14,18989900.0,1.614720e+10,1.940670e+13,...,0.001170,0.004335,0.006892,0.000260,0.000130,0.000000,0.000043,0,0.003858,0.023450
48,BY,103,47,48469,59291000.0,9.132640e+10,1.609100e+14,9410440.0,1.134750e+10,1.733510e+13,...,0.001637,0.013521,0.006602,0.000264,0.000053,0.000053,0.000000,0,0.009665,0.025351
49,BZ,103,27,38457,41007500.0,5.818550e+10,9.443270e+13,8321450.0,8.325640e+09,1.149750e+13,...,0.000999,0.010561,0.006565,0.000642,0.000214,0.000000,0.000000,0,0.008991,0.028329
50,CA,95,48,39832,47098400.0,6.859570e+10,1.107350e+14,5232780.0,5.720010e+09,7.957900e+12,...,0.001460,0.011745,0.005508,0.000796,0.000265,0.000133,0.000000,0,0.008361,0.021367
51,CB,106,52,62482,73285600.0,1.162820e+11,2.104250e+14,8639180.0,8.656390e+09,1.302070e+13,...,0.002519,0.013593,0.006298,0.000840,0.000052,0.000052,0.000052,0,0.007033,0.018526
52,CC,117,49,53171,58425400.0,8.287440e+10,1.336760e+14,9912660.0,1.023190e+10,1.438660e+13,...,0.001725,0.009817,0.008627,0.000416,0.000059,0.000000,0.000000,0,0.009817,0.040933